### ISSUE TITLE
ZeroDivisionError: division by zero error when using HiRes fix

### ISSUE THREAD

**Issue by Volnovik** [Haoming02/sd-webui-resharpen#10]
Getting error during HiRes fix with HiRes fix with any checkbox selected other than Flat for HiRes.

ReSharpen version: 
f79e14d6

Error:
    Traceback (most recent call last):
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\processing.py", line 981, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\processing.py", line 1344, in sample
        return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\processing.py", line 1429, in sample_hr_pass
        samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\sd_samplers_kdiffusion.py", line 172, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\sd_samplers_kdiffusion.py", line 172, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\repositories\k-diffusion\k_diffusion\sampling.py", line 555, in sample_dpmpp_sde
        callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-resharpen\scripts\resharpen.py", line 26, in hijack_callback
        d["x"] += delta * apply_scaling(
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-resharpen\scripts\res_scaling.py", line 8, in apply_scaling
        ratio = float(current_step / total_steps)
    ZeroDivisionError: division by zero
[f79e14d6](https://github.com/Haoming02/sd-webui-resharpen/commit/f79e14d67f70285e7a888b2d6bc632dcd38d8e3d)

SDWebUI Version: v1.9.4
Windows
Installed extensions:
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git
sd-webui-cd-tuner | https://github.com/hako-mikan/sd-webui-cd-tuner.git
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git
sd-webui-freeu | https://github.com/ljleb/sd-webui-freeu
sd-webui-incantations | https://github.com/v0xie/sd-webui-incantations.git
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing.git
sd-webui-inpaint-anything | https://github.com/Uminosachi/sd-webui-inpaint-anything.git
sd-webui-kohya-hiresfix | https://github.com/wcde/sd-webui-kohya-hiresfix.git
sd-webui-lama-cleaner-masked-content | https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content.git
sd-webui-mosaic-outpaint | https://github.com/Haoming02/sd-webui-mosaic-outpaint.git
sd-webui-resharpen | https://github.com/Haoming02/sd-webui-resharpen.git
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything.git
sd-webui-tabs-extension | https://github.com/Haoming02/sd-webui-tabs-extension.git
sd-webui-yandere-inpaint-masked-content | https://github.com/light-and-ray/sd-webui-yandere-inpaint-masked-content.git
sd_civitai_extension | https://github.com/civitai/sd_civitai_extension
stable-diffusion-webui-dataset-tag-editor | https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git
webui-fooocus-prompt-expansion | https://github.com/power88/webui-fooocus-prompt-expansion.git

**Comment by Volnovik** [comment]
Same error in img2img and inpaint
